### ISSUE TITLE
Problem preprocessing ERA5

### ISSUE THREAD

**Issue by ahernanzl** [robbiewatt1/ClimateDiffuse#3]
Hello, 
I'm finding this error when preprocessing the ERA5 files:

  _File "preprocessing_subsample.py", line 16, in <module>
    parser.add_argument('--remove_files', metavar='remove_files', action=argparse.BooleanOptionalAction)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'_

Any solution?
Thank you!

**Comment by lm2612** [comment]
Hi
What python version are you using? 
From [this stackoverflow question](https://stackoverflow.com/questions/70242395/run-capital-gains-command-and-get-erro-attributeerror-module-argparse-has-no) it looks like you may need python > 3.9 for `argparse.BooleanOptionalAction`. 
We used python3.10. I would suggest trying with 3.10 as you might run into other issues later with an older version. Hope that helps!

**Comment by ahernanzl** [comment]
Thank you very much, it solved the problem.
